name: Spring Deploy
on: 
  push:
    branches:
      - main
jobs:
  deploy: 
    runs-on: self-hosted
    
    steps:
      # 소스 체크#
      - name: Checkout
        uses: actions/checkout@v4
      # 프로젝트 구조 확인#
      - name: Check Project Structure
        run: |
          echo "=== 현재 위치 ==="
          pwd

          echo "=== 프로젝트 목록 ==="
          ls -al

      #자바 확인#
      - name: Java version
        run: |
          java -version
          mvn -version

      # Maven war파일 만들기 #
      - name: Maven Build
        run: |
          mvn clean package -DskipTests
          
      # WAR 확인 #
      - name: Check War
        run: |
          echo "=== 생성확인 ==="
          ls -al target

       # 빌드된 war 파일을 톰캣 webapps 폴더로 복사 #
      - name: Deploy to Tomcat
        run: |
          cp target/SpringLastProject.war /home/sist/apache-tomcat-9.0.120/webapps/SpringLastProject.war
          
          # 톰캣 재시작
          sudo systemctl restart tomcat9
          
