name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
  # 모든 명령 기본 작업 디렉토리 설정
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Maven Build
        run: mvn clean package -DskipTests
      - name: Stop Tomcat
        run: |
          /home/sist/apache-tomcat-9.0.120/bin/shutdown.sh || true
          sleep 3
          pkill -9 -f tomcat || true
      - name: Remove Old war
        run: |
          rm -rf /home/sist/apache-tomcat-9.0.120/webapps/SpringLast*
      - name: Deploy New war
        run: |
          cp target/*.war /home/sist/apache-tomcat-9.0.120/webapps/SpringLastProject.war
      - name: Start Tomcat
        env: 
          RUNNER_TRACKING_ID: ""
        run: |
          nohup /home/sist/apache-tomcat-9.0.120/bin/startup.sh
          sleep 5
